// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/8 17:31:57
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/git/nuxt-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/plugins/**/*.{js,ts,mjs}","/Users/mac/git/nuxt-blog/composables/**/*.{js,ts,mjs}","/Users/mac/git/nuxt-blog/utils/**/*.{js,ts,mjs}","/Users/mac/git/nuxt-blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/git/nuxt-blog/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["16"] = "/Users/mac/git/nuxt-blog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;